// Consent-review only. Bracketed fields are placeholders, not verified credentials.
const tutors = [
 {name:'C*** O***',initials:'CO',school:'University of Chicago',degree:'학부 재학 · [전공 확인 예정]',tags:['SAT 1570','AP 5점','SAT·교과'],subjects:['SAT Math','SAT Reading & Writing','AP [담당 과목 확인]'],experience:'SAT·교과 지도 [N]년',detail:'누적 지도 학생 [N]명'},
 {name:'J*** H***',initials:'JH',school:'MIT · Stanford',degree:'MIT 건축학 [학위 상태 확인] · Stanford 학사',tags:['MIT 건축','Stanford 출신','포트폴리오'],subjects:['건축·디자인 포트폴리오','작품 구성','지원 글 지도'],experience:'포트폴리오 지도 [N]년',detail:'MIT 건축 스튜디오 TA 경험'},
 {name:'G*** I***',initials:'GI',school:'London School of Economics',degree:'정치학 박사과정',tags:['LSE 박사과정','대학 교육 경험','Academic Writing'],subjects:['정치학·정치경제','Academic Writing','영국 대학 지원 글'],experience:'LSE 교육 경력 [N]년',detail:'개인 튜터링 경력 [N]년'}
];
function tutorCard(t,compact=false){return `<article class="profile-card"><div class="profile-photo"><b aria-hidden="true">${t.initials}</b><small>사진 승인 대기</small></div><p class="profile-kind">선생님 · 학력</p><p class="profile-school">${t.school}</p><p class="profile-role">${t.degree}</p><h3>${t.name}</h3><p class="profile-topics">${t.subjects.join(' · ')}</p><div class="profile-proof">${t.name==='C*** O***'?'본인 SAT 1570 · AP 5점':t.name==='J*** H***'?'MIT 건축 스튜디오 TA 경험':'LSE 대학 교육 경험'}</div>${compact?'':`<p class="profile-detail">${t.experience}${t.name==='J*** H***'?'':`<br>${t.detail}`}</p>`}</article>`;}
function tutorCards(compact=false){return `<div class="profile-grid">${tutors.map(t=>tutorCard(t,compact)).join('')}</div>`;}
function tutorInquiry(){return `<div class="tutor-inquiry"><div><h3>찾는 과목이 따로 있으신가요?</h3><p>소개된 선생님 외에도, 학생의 과목과 목표에 맞는 선생님을 문의해 주세요.</p></div><a class="textlink" href="#contact?service=tutoring">선생님 매칭 문의 ↗</a></div>`;}
function tutorSection(){return `<section class="section wrap featured-tutors"><div class="section-heading"><div><p class="eyebrow">MEET YOUR TUTOR</p><h2>이런 선생님을 만나보세요.</h2></div><p>학교 공부부터 새로운 관심 분야까지.</p></div>${tutorCards()}${tutorInquiry()}</section>`;}
